CREATE DATABASE SQL_PHAMHONGSON
GO
USE SQL_PHAMHONGSON
GO

CREATE TABLE PHONGBAN (
	MAPB CHAR(10) PRIMARY KEY,
	TENPB CHAR(50),
	DIACHI CHAR(100),
	SODT CHAR(20),
	CHUCNANG CHAR(100),
	SONV INT
);
CREATE TABLE CHUCVU(
	MACV CHAR(10) PRIMARY KEY,
	TENCV CHAR(50),
	HESOCV FLOAT,
	GHICHU CHAR(100)
);

CREATE TABLE NHANVIEN(
	MANV CHAR(10) PRIMARY KEY,
	HOTEN CHAR(50),
	NGAYSINH DATE,
	GIOITINH CHAR(5),
	NOISINH CHAR(50),
	HSL FLOAT,
	MAPB CHAR(10) REFERENCES PHONGBAN(MAPB),
	MACV CHAR(10) REFERENCES CHUCVU(MACV)
);
CREATE TABLE QUATRINH(
    MAQT CHAR(10) PRIMARY KEY,
    MANV CHAR(10) REFERENCES NHANVIEN(MANV),
    TUNGAY DATE,
    DENNGAY DATE,
    VITRI CHAR(50),
    GHICHU CHAR(100),
);
CREATE TABLE LUONG(
    MALUONG CHAR(10) PRIMARY KEY,
    THANGNAM CHAR(7),
    MANV CHAR(10) REFERENCES NHANVIEN(MANV),
    LUONGCB FLOAT,
    THUONG FLOAT,
    KHAUTRU FLOAT,
    TONGLINH FLOAT
);

--CAU 2
INSERT INTO PHONGBAN VALUES ('PB01','Nhansu','HN','0123456789','Quan ly nhan su',0)
INSERT INTO PHONGBAN VALUES ('PB02','KeToan','HCM','0987654321','Quan ly tai chinh',0)

INSERT INTO CHUCVU VALUES ('CV01','Nhan Vien',1.0,'')
INSERT INTO CHUCVU VALUES ('CV02','Quan Ly',2.0,'')

INSERT INTO NHANVIEN VALUES ('NV01','Tran Van A','1990-02-02','Nam','Ha Noi',2.5,'PB01','CV01')
INSERT INTO NHANVIEN VALUES ('NV02','Nguyen Thi B','1995-05-05','Nu','HCM',3.0,'PB02','CV02')

INSERT INTO QUATRINH VALUES ('QT01','NV01','2020-01-01','2021-01-01','Nhan vien','')
INSERT INTO QUATRINH VALUES ('QT02','NV02','2021-01-01','2022-01-01','Quan ly','')

INSERT INTO LUONG VALUES ('L01','11/2025','NV01',6000000,500000,200000,0)
INSERT INTO LUONG VALUES ('L02','11/2025','NV02',8000000,700000,300000,0)

SELECT * FROM PHONGBAN
EXEC SP_HELP PHONGBAN
SELECT * FROM CHUCVU
EXEC SP_HELP CHUCVU
SELECT * FROM NHANVIEN
EXEC SP_HELP NHANVIEN
SELECT * FROM QUATRINH
EXEC SP_HELP QUATRINH
SELECT * FROM LUONG
EXEC SP_HELP LUONG

--CAU 3
CREATE OR ALTER VIEW V_THONGTINLUONGNV
AS
SELECT 
	NHANVIEN.MANV, NHANVIEN.HOTEN, NHANVIEN.NGAYSINH, NHANVIEN.GIOITINH, NHANVIEN.NOISINH, NHANVIEN.HSL, NHANVIEN.MAPB, NHANVIEN.MACV,
	LUONG.LUONGCB, LUONG.THUONG, LUONG.KHAUTRU, CHUCVU.HESOCV, 
	LUONG.LUONGCB * (NHANVIEN.HSL+ CHUCVU.HESOCV) + LUONG.THUONG - LUONG.KHAUTRU AS TONGLINH
FROM NHANVIEN, LUONG, CHUCVU
WHERE LUONG.MANV = NHANVIEN.MANV AND CHUCVU.MACV = NHANVIEN.MACV;

SELECT * FROM V_THONGTINLUONGNV

--CAU 3B
CREATE OR ALTER VIEW V_TONGNHANVIENTHEOTUNGPHONG
AS
SELECT
	PHONGBAN.MAPB, PHONGBAN.TENPB,
	COUNT(*) AS SLNV
FROM PHONGBAN, NHANVIEN
WHERE PHONGBAN.MAPB = NHANVIEN.MAPB
GROUP BY PHONGBAN.MAPB, PHONGBAN.TENPB

SELECT * FROM V_TONGNHANVIENTHEOTUNGPHONG

--CAU 4
CREATE PROCEDURE SP_SUALUONG
	@MANV CHAR(10) = MANV,
	@THUONG FLOAT = THUONG,
    @KHAUTRU FLOAT = KHAUTRU
AS
BEGIN
	UPDATE LUONG
	SET THUONG = @THUONG,
		KHAUTRU = @KHAUTRU
	WHERE @MANV = MANV
END

EXEC SP_SUALUONG 'NV01', 900000, 250000;
SELECT * FROM LUONG WHERE MANV = 'NV01';

CREATE OR ALTER PROCEDURE SP_XOADULIEUCHUCVU
	@MACV CHAR(10) = MACV
AS
BEGIN
	DELETE FROM CHUCVU WHERE MACV = @MACV;
END;

--CAU 5
CREATE OR ALTER TRIGGER Trg_TINHTOANTONGLINHLUONG
ON LUONG
AFTER INSERT, UPDATE
AS
BEGIN
	UPDATE LUONG
	SET TONGLINH = LUONG.LUONGCB * (( SELECT HSL FROM NHANVIEN WHERE NHANVIEN.MANV = LUONG.MANV) + 
	(SELECT HESOCV FROM CHUCVU WHERE CHUCVU.MACV = (SELECT MACV FROM NHANVIEN WHERE NHANVIEN.MANV = LUONG.MANV))) + LUONG.THUONG - LUONG.KHAUTRU
	WHERE MANV IN (SELECT MANV FROM inserted)
END;

CREATE PROCEDURE SP_CHOBIETTONGLUONG
	@LUACHON INT,
	@THANGNAM CHAR(7) 
AS
BEGIN
	IF @LUACHON = 1
	BEGIN
		SELECT
		PHONGBAN.MAPB,
		PHONGBAN.TENPB,
		(
			SELECT SUM(LUONG.TONGLINH)
			FROM LUONG
			WHERE LUONG.MANV IN (
				SELECT MANV FROM NHANVIEN
				WHERE NHANVIEN.MAPB = PHONGBAN.MAPB
			)
			AND LUONG.THANGNAM = @THANGNAM
		) AS TONG_LUONG_PHONGBAN
		FROM PHONGBAN;
	END

	ELSE IF @LUACHON = 2
	BEGIN
		SELECT 
			CHUCVU.MACV,
			CHUCVU.TENCV,
			(
				SELECT SUM(LUONG.TONGLINH)
				FROM LUONG
				WHERE LUONG.MANV IN (
					SELECT MANV FROM NHANVIEN
					WHERE NHANVIEN.MACV = CHUCVU.MACV
				)
				AND LUONG.THANGNAM = @THANGNAM
			) AS TONG_LUONG_CHUCVU
			FROM CHUCVU;
		END
	PRINT N'LUA CHON KHONG HOP LE'
END
